import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import {Outfit} from "next/font/google";

const outfit = Outfit({subsets: ['latin']})

export const metadata = {
  title: "PDF-Anywhere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
    </>
  );
}
