"use client"
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexProvider, ConvexReactClient } from "convex/react";
import "./globals.css";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"] });

// Initialize Convex client
const convex = new ConvexReactClient(process.env.NEXT_PUBLIC_CONVEX_URL);

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ConvexProvider client={convex}>
        <html lang="en">
          <head>
            <title>PDF-Anywhere</title>
            <meta
              name="description"
              content="Generated by create next app"
            />
          </head>
          <body className={outfit.className}>{children}</body>
        </html>
      </ConvexProvider>
    </ClerkProvider>
  );
}
